[versions]
com-github-tanyaofei-devtools = "0.1.7-SNAPSHOT"
com-mojang-authlib = "4.0.43"
com-mojang-brigadier = "1.1.8"
commons-io = "2.15.1"
dev-jorel-commandapi = "12.0.0"
io-netty = "4.1.82.Final"
io-papermc-paper-api = "1.21.7-R0.1-SNAPSHOT"
org-projectlombok = "1.18.46"
openinv = "5.3.0"
placeholderapi = "2.11.7"
org-spigotmc-spigot-v1-20-1 = "1.20.1-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-20-2 = "1.20.2-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-20-4 = "1.20.4-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-20-6 = "1.20.6-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21 = "1.21-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-1 = "1.21.1-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-3 = "1.21.3-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-4 = "1.21.4-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-5 = "1.21.5-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-6 = "1.21.6-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-7 = "1.21.7-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-21-10 = "1.21.10-R0.1-SNAPSHOT"
org-spigotmc-spigot-v1-26-1 = "26.1.2-R0.1-SNAPSHOT"

[libraries]
com-github-tanyaofei-devtools-devtools-core = { module = "com.github.tanyaofei.devtools:devtools-core", version.ref = "com-github-tanyaofei-devtools" }
com-github-tanyaofei-devtools-devtools-command = { module = "com.github.tanyaofei.devtools:devtools-command", version.ref = "com-github-tanyaofei-devtools" }
com-github-tanyaofei-devtools-devtools-database = { module = "com.github.tanyaofei.devtools:devtools-database", version.ref = "com-github-tanyaofei-devtools" }
com-mojang-authlib = { module = "com.mojang:authlib", version.ref = "com-mojang-authlib" }
com-mojang-brigadier = { module = "com.mojang:brigadier", version.ref = "com-mojang-brigadier" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
dev-jorel-commandapi-paper-core = { module = "dev.jorel:commandapi-paper-core", version.ref = "dev-jorel-commandapi" }
io-netty-netty-transport = { module = "io.netty:netty-transport", version.ref = "io-netty" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-api" }
openinv-openinv = { module = "com.github.jikoo:OpenInv", version.ref = "openinv" }
org-projectlombok-lombok = { module = "org.projectlombok:lombok", version.ref = "org-projectlombok" }
placeholderapi-placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
org-spigotmc-spigot-v1-20-1 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-20-1" }
org-spigotmc-spigot-v1-20-2 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-20-2" }
org-spigotmc-spigot-v1-20-4 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-20-4" }
org-spigotmc-spigot-v1-20-6 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-20-6" }
org-spigotmc-spigot-v1-21 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21" }
org-spigotmc-spigot-v1-21-1 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-1" }
org-spigotmc-spigot-v1-21-3 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-3" }
org-spigotmc-spigot-v1-21-4 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-4" }
org-spigotmc-spigot-v1-21-5 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-5" }
org-spigotmc-spigot-v1-21-6 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-6" }
org-spigotmc-spigot-v1-21-7 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-7" }
org-spigotmc-spigot-v1-21-10 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-21-10" }
org-spigotmc-spigot-v1-26-1 = { module = "org.spigotmc:spigot", version.ref = "org-spigotmc-spigot-v1-26-1" }
